### ISSUE TITLE
ESP32 Arduino IDE Driver issues OSX Big Sur, Catalina 10.16 and on

### ISSUE THREAD

**Issue by udellc** [OPEnSLab-OSU/Nanolux#1]
We couldn't get the ESP32 working with Arduino IDE for OS 10.16
John will post the fix. This should be solved in a future release of the Arduino IDE version, but in the meantime, follow this:

**Comment by johnczontos** [comment]
To fix this issue, I followed these steps:
-Uninstalled and re-installed the Arduino IDE.
-then followed [this guide](https://www.youtube.com/watch?v=zkyoghpT8_U) to make solve all compatibility issues with MAC OSX
-(also, had to switch out my USB cable for a USB cable with a data line.)

**Comment by goldswol** [comment]
Our team found no instances of this bug during development
