### ISSUE TITLE
Update the Wiki

### ISSUE THREAD

**Issue by kalidasv** [OPEnSLab-OSU/Nanolux#21]
https://github.com/kalidasv/Nanolux/wiki

**Comment by kalidasv** [comment]
Clone the wiki locally:
https://github.com/kalidasv/Nanolux.wiki.git

**Comment by kalidasv** [comment]
For the owner(you are OREPO):
https://gist.github.com/larrybotha/10650410

**Comment by billychili** [comment]
Finished merging

**Comment by billychili** [comment]
Finished merging
